name: breakout_addiction
description: Android-first recovery app for compulsive pornography use.
publish_to: "none"

version: 0.1.0+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2
  url_launcher: ^6.3.0
  flutter_local_notifications: ^21.0.0
  flutter_timezone: ^5.0.2
  timezone: ^0.11.0
  http: ^1.2.2
  in_app_purchase: ^3.3.0
  in_app_purchase_android: ^0.5.0
  video_player: ^2.9.5
  path_provider: ^2.1.5
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true


flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/branding/breakout_app_icon.png"
  adaptive_icon_background: "#02071F"
  adaptive_icon_foreground: "assets/branding/breakout_app_icon_adaptive_foreground.png"
  adaptive_icon_foreground_inset: 0
  min_sdk_android: 21
